ALTER TABLE `blocks`
  ADD FOREIGN KEY (`pageId`)
  REFERENCES `pages`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `blockMetas`
  ADD FOREIGN KEY (`blockId`)
  REFERENCES `blocks`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `pages`
  ADD FOREIGN KEY (`siteId`)
  REFERENCES `sites`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `blocks`
  ADD FOREIGN KEY (`siteId`)
  REFERENCES `sites`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `usersSites`
   ADD FOREIGN KEY (`siteId`)
 REFERENCES `sites`(`id`)
   ON DELETE RESTRICT
   ON UPDATE RESTRICT;

ALTER TABLE `usersSites`
  ADD FOREIGN KEY (`userId`)
  REFERENCES `users`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `pageTypeSites`
  ADD FOREIGN KEY (`pageTypeId`)
REFERENCES `pageTypes`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `pageTypeSites`
  ADD FOREIGN KEY (`siteId`)
REFERENCES `sites`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `blockTypeSites`
  ADD FOREIGN KEY (`blockTypeId`)
REFERENCES `blockTypes`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `blockTypeSites`
  ADD FOREIGN KEY (`siteId`)
REFERENCES `sites`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `pages`
  ADD FOREIGN KEY (`pageTypeId`)
REFERENCES `pageTypes` (`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `blocks`
  ADD FOREIGN KEY (`blockTypeId`)
REFERENCES `blockTypes`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `mailServers`
  ADD FOREIGN KEY (`siteId`)
REFERENCES `sites`(`id`) ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `mailServers`
  ADD FOREIGN KEY (`userId`)
REFERENCES `users`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `mailMessage`
  ADD FOREIGN KEY (`mailAccountId`)
REFERENCES `mailAccount`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `mailAccount`
  ADD FOREIGN KEY (`siteId`)
REFERENCES `sites`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `mailAccount`
  ADD FOREIGN KEY (`userId`)
REFERENCES `users`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `mailAccount`
  ADD FOREIGN KEY (`mailServerId`)
REFERENCES `mailServers` (`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `mailMessage`
  ADD FOREIGN KEY (`contactId`)
REFERENCES `mailContacts` (`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `eventLog`
  ADD FOREIGN KEY (`siteId`)
REFERENCES `sites`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `eventLog`
  ADD FOREIGN KEY (`userId`)
REFERENCES `users`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;