ALTER TABLE `blocks`
  ADD FOREIGN KEY (`pageId`)
REFERENCES `pages`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `blocks`
  ADD FOREIGN KEY (`siteId`)
REFERENCES `sites`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `blocks`
  ADD FOREIGN KEY (`blockTypeId`)
REFERENCES `blockTypes`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;