ALTER TABLE `mailAccount`
  ADD FOREIGN KEY (`siteId`)
REFERENCES `sites`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `mailAccount`
  ADD FOREIGN KEY (`userId`)
REFERENCES `users`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `mailAccount`
  ADD FOREIGN KEY (`mailServerId`)
REFERENCES `mailServers` (`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;