ALTER TABLE `navigation`
  ADD FOREIGN KEY (`siteId`)
REFERENCES `sites`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `navigation`
  ADD FOREIGN KEY (`pageId`)
REFERENCES `pages`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `navigation`
  ADD FOREIGN KEY (`childPageId`)
REFERENCES `pages`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;
