ALTER TABLE `viewSite`
  ADD FOREIGN KEY (`siteId`)
REFERENCES `sites`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `viewSite`
  ADD FOREIGN KEY (`visitorId`)
REFERENCES `visitors`(`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;